GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/4

###
DELETE http://localhost:3001/api/persons/606336c03f371353f8b600ca

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Bob Ross",
  "number": "123-123-123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Al",
  "number": "123-123-123"
} 

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
	"name": "Dan Abramov",
	"number": "12-43-234345"
}

###

POST http://localhost:3001/api/persons
Contet-Type: application/json

{
  "name": "Bob Ross"
}

###

POST http://localhost:3001/api/persons
Contet-Type: application/json

{
  "number": "123-123-123"
}